### ISSUE TITLE
Cannot use transform on a TU without LU in HU Editor

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#1012]
### Is this a bug or feature request?
bug
### What is the current behavior?
Cannot use transform on a TU without LU in HU Editor
#### Which are the steps to reproduce?
1. go to receipt candidates window (540196)
2. select a line and Receive HUs
3. you can either receive only TUs, or TUs and LUs
4. if you received only TUs, select a TU and use transform
=> error
5. if you received LUs, select a TU, transform and use TU to new TUs, select the new TU and use transform
=> error
"Failed invoking private de.metas.ui.web.window.datatypes.LookupValuesList de.metas.ui.web.handlingunits.process.WEBUI_M_HU_Transform.getActions() using [Ljava.lang.Object;@7aeb9f74"

<details/>
"org.adempiere.exceptions.AdempiereException: Failed invoking private de.metas.ui.web.window.datatypes.LookupValuesList de.metas.ui.web.handlingunits.process.WEBUI_M_HU_Transform.getActions() using [Ljava.lang.Object;@7aeb9f74"
1
:
"	at de.metas.ui.web.process.adprocess.WebuiProcessClassInfo.retriveLookupValues(WebuiProcessClassInfo.java:267)"
2
:
"	at de.metas.ui.web.process.adprocess.WebuiProcessClassInfo.lambda$createParamLookupValuesProvider$3(WebuiProcessClassInfo.java:235)"
3
:
"	at de.metas.ui.web.window.descriptor.ListLookupDescriptor.retrieveEntities(ListLookupDescriptor.java:130)"
4
:
"	at de.metas.ui.web.window.model.lookup.LookupDataSourceAdapter.findEntities(LookupDataSourceAdapter.java:100)"
5
:
"	at de.metas.ui.web.window.model.lookup.LookupDataSourceAdapter.findEntities(LookupDataSourceAdapter.java:78)"
6
:
"	at de.metas.ui.web.window.model.lookup.LookupDataSource.findEntities(LookupDataSource.java:58)"
7
:
"	at de.metas.ui.web.window.model.DocumentField.getLookupValues(DocumentField.java:424)"
8
:
"	at de.metas.ui.web.window.model.Document.getFieldLookupValues(Document.java:1489)"
9
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.getParameterLookupValues(ADProcessInstanceController.java:208)"
10
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$getParameterDropdown$12(ProcessRestController.java:335)"
11
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceReadonly(ADProcessInstancesRepository.java:386)"
12
:
"	at de.metas.ui.web.process.ProcessRestController.getParameterDropdown(ProcessRestController.java:335)"
13
:
"	at sun.reflect.GeneratedMethodAccessor606.invoke(Unknown Source)"
14
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
15
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
16
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
17
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
18
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
19
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
20
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
21
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
22
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
23
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
24
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
25
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
26
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
27
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
28
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
29
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
30
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
31
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
32
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
33
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
34
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
35
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
36
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
37
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
38
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
39
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
40
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
41
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
42
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
43
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
44
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
45
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
46
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
47
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
48
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
49
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
50
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
51
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
52
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
53
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
54
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
55
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
56
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
57
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
58
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
59
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
60
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
61
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
62
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
63
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
64
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
65
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
66
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
67
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
68
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
69
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
70
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
71
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
72
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
73
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
74
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
75
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
76
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
77
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
78
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
79
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
80
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
81
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
82
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
83
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
84
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
85
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
86
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
87
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
88
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
89
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
90
:
"	at java.lang.Thread.run(Thread.java:748)"
91
:
"Caused by: java.lang.NullPointerException"
92
:
"	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)"
93
:
"	at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.add(ImmutableCollection.java:477)"
94
:
"	at com.google.common.collect.ImmutableSet$Builder.add(ImmutableSet.java:486)"
95
:
"	at de.metas.ui.web.handlingunits.HUEditorRowFilter$Builder.excludeHUId(HUEditorRowFilter.java:89)"
96
:
"	at de.metas.ui.web.handlingunits.process.WebuiHUTransformParametersFiller.getActionTypesForTUs(WebuiHUTransformParametersFiller.java:229)"
97
:
"	at de.metas.ui.web.handlingunits.process.WebuiHUTransformParametersFiller.getActions(WebuiHUTransformParametersFiller.java:165)"
98
:
"	at de.metas.ui.web.handlingunits.process.WEBUI_M_HU_Transform.getActions(WEBUI_M_HU_Transform.java:139)"
99
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
</details>

note: it works in handling units editor window (540189)
### What is the expected or desired behavior?
should work, no errors

**Comment by metas-lc** [comment]
IT
1. repeated the testcase above
=> works fine, you can use transform on TUs without LUs OK

2. just to make sure transform works in general, for the other cases
=> transform CU on TU with LU - works OK
=> transform CU on TU without LU - works OK
=> transform CU without TU/LU - works OK
=> transform TU on LU - works OK
=> transform LU - works OK
