### ISSUE TITLE
Error after using "Create Purchase Order" action and trying to add / change orderlines

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1048]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Found during IT for #1047:

When you try to add / change orderlines  after using "Create Purchase Order" action, you sometimes get an error.
#### Which are the steps to reproduce?
1. Create a sales order with sev. orderlines 
2. Close the batch entry
3. Use the "Create Purchase Order" for one of the orderlines
4. Try opening the batch entry again or try changing the qty TU an orderline:

<details>

```
{timestamp: 1536928786979, status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
exception: "org.adempiere.exceptions.AdempiereException"
message: "String document IDs cannot be converted to int: L-6-2156423-rw"
path: "/rest/api/window/143/L-6-2156423-rw/187/quickInput"
status: 500
timestamp: 1536928786979
trace: [,…]
[0 … 99]
0: "org.adempiere.exceptions.AdempiereException: String document IDs cannot be converted to int: L-6-2156423-rw"
1: "	at de.metas.ui.web.window.datatypes.DocumentId$StringDocumentId.toInt(DocumentId.java:402)"
2: "	at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.buildSqlWhereClause(SqlDocumentQueryBuilder.java:404)"
3: "	at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.getSqlWhereAndParams(SqlDocumentQueryBuilder.java:363)"
4: "	at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.buildSql(SqlDocumentQueryBuilder.java:300)"
5: "	at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.getSqlAndParams(SqlDocumentQueryBuilder.java:280)"
6: "	at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.getSql(SqlDocumentQueryBuilder.java:267)"
7: "	at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.retriveDocuments(SqlDocumentsRepository.java:183)"
8: "	at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.retrieveDocument(SqlDocumentsRepository.java:268)"
9: "	at de.metas.ui.web.window.model.DocumentQuery$Builder.retriveDocumentOrNull(DocumentQuery.java:196)"
10: "	at de.metas.ui.web.window.model.DocumentCollection.retrieveRootDocumentFromRepository(DocumentCollection.java:353)"
11: "	at de.metas.ui.web.window.model.DocumentCollection.lambda$getOrLoadDocument$2(DocumentCollection.java:196)"
12: "	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)"
13: "	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)"
14: "	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)"
15: "	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)"
16: "	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)"
17: "	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)"
18: "	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)"
19: "	at de.metas.ui.web.window.model.DocumentCollection.getOrLoadDocument(DocumentCollection.java:194)"
20: "	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentReadonly(DocumentCollection.java:213)"
21: "	at de.metas.ui.web.quickinput.WindowQuickInputRestController.lambda$create$1(WindowQuickInputRestController.java:159)"
22: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)"
23: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
24: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
25: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
26: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
27: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
28: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)"
29: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:475)"
30: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)"
31: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
32: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
33: "	at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)"
34: "	at de.metas.ui.web.quickinput.WindowQuickInputRestController.create(WindowQuickInputRestController.java:158)"
35: "	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
36: "	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
37: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
38: "	at java.lang.reflect.Method.invoke(Method.java:498)"
39: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
40: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
41: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
42: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
43: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
44: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
45: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
46: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
47: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
48: "	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)"
49: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)"
50: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
51: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
52: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
53: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
54: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
55: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
56: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
57: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
58: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
59: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
60: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
61: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
62: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
63: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
64: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
65: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
66: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
67: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
68: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
69: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
70: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
71: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
72: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
73: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
74: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
75: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
76: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
77: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
78: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
79: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
80: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
81: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
82: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
83: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
84: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
85: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
86: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
87: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
88: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
89: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
90: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
91: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
92: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
93: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
94: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
95: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
96: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
97: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
98: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
99: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
[100 … 114]
100: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
101: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
102: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
103: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
104: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
105: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
106: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
107: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
108: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
109: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
110: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
111: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
112: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
113: "	at java.lang.Thread.run(Thread.java:748)"
114: ""
```
</details>

After cache reset it works fine again, also after waiting a few mins you can change / add orderlines again without problems.
### What is the expected or desired behavior?

No error, shall work.

**Comment by teosarca** [comment]
@metas-dh  this looks like a frontend issue. It would be nice if we could find out a pattern... or to have an example on w101.
