### ISSUE TITLE
New Org cannot be created anymore

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#1051]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, it is not possible to create a new Org.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall be fixed.

<details>
```
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
message
:
"Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
↵Bitte leiten Sie diese Meldung an metas weiter:↵↵Assumption failure: This instance needs to have a DocumentId; this=Document{tableName=AD_Org, NEW=true, windowNo=4, writable=false, valid=Invalid-Initial('Mandatory field Name not filled'), validOnCheckout=Invalid-Initial('Mandatory field Name not filled'), saveStatus=DocumentSaveStatus{saved=false, deleted=false, hasChangesToBeSaved=true, error=false, reason=Mandatory field Name not filled}, saveStatusOnCheckout=DocumentSaveStatus{saved=false, deleted=false, hasChangesToBeSaved=true, error=false, reason=Mandatory field Name not filled}}"
path
:
"/rest//api/window/110/1000003"
status
:
500
timestamp
:
1537253216320
trace
:
[,…]
0
:
"org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
"
1
:
"Bitte leiten Sie diese Meldung an metas weiter:"
2
:
""
3
:
"Assumption failure: This instance needs to have a DocumentId; this=Document{tableName=AD_Org, NEW=true, windowNo=4, writable=false, valid=Invalid-Initial('Mandatory field Name not filled'), validOnCheckout=Invalid-Initial('Mandatory field Name not filled'), saveStatus=DocumentSaveStatus{saved=false, deleted=false, hasChangesToBeSaved=true, error=false, reason=Mandatory field Name not filled}, saveStatusOnCheckout=DocumentSaveStatus{saved=false, deleted=false, hasChangesToBeSaved=true, error=false, reason=Mandatory field Name not filled}}"
4
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
5
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
6
:
"	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)"
7
:
"	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)"
8
:
"	at org.adempiere.util.Check.mkEx(Check.java:112)"
9
:
"	at org.adempiere.util.Check.throwOrLogEx(Check.java:123)"
10
:
"	at org.adempiere.util.Check.assume(Check.java:170)"
11
:
"	at org.adempiere.util.Check.assumeNotNull(Check.java:260)"
12
:
"	at org.adempiere.util.Check.assumeNotNull(Check.java:251)"
13
:
"	at de.metas.ui.web.window.model.Document.getDocumentId(Document.java:986)"
14
:
"	at de.metas.ui.web.window.controller.DocumentPermissionsHelper.assertCanView(DocumentPermissionsHelper.java:147)"
15
:
"	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentReadonly(DocumentCollection.java:216)"
16
:
"	at de.metas.ui.web.window.controller.WindowRestController.getData(WindowRestController.java:237)"
17
:
"	at de.metas.ui.web.window.controller.WindowRestController.getData(WindowRestController.java:192)"
18
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
19
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
20
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
21
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
22
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
23
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
24
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
25
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
26
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
27
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
28
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
29
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
30
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
31
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
32
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
33
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
34
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
35
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
36
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
37
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
38
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
39
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
40
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
41
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
42
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
43
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
44
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
45
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
46
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
47
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
48
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
49
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
50
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
51
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
52
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
53
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
54
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
55
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
57
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
58
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
60
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
61
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
62
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
63
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
65
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
66
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
67
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
69
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
70
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
71
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
73
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
74
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
75
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
76
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
77
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
78
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
79
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
81
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
82
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
83
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
84
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
85
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
86
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
87
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
88
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
89
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
90
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
91
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
92
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
93
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
94
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
95
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
96
:
"	at java.lang.Thread.run(Thread.java:748)"
97
:
""
```
</details>

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new org can be created without errors: OK
* new org can e.g. be selected as org in new product: OK
* org * still cannot be selected for user that has no rights / access to all orgs, e.g. when creating new bpartner: OK
