### ISSUE TITLE
Process picking action not working 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1074]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you try to use the process picking action, you get

<details>
```
{timestamp: 1540213388014, status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
exception: "org.adempiere.exceptions.AdempiereException"
message: "Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
↵Bitte leiten Sie diese Meldung an metas weiter:↵↵Assumption failure: pickingCandidates is not empty"
path: "/rest/api/process/ADP_540810/1000625/start"
status: 500
timestamp: 1540213388014
trace: [,…]
[0 … 99]
0: "org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
"
1: "Bitte leiten Sie diese Meldung an metas weiter:"
2: ""
3: "Assumption failure: pickingCandidates is not empty"
4: "	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
5: "	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
6: "	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)"
7: "	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)"
8: "	at de.metas.util.Check.mkEx(Check.java:112)"
9: "	at de.metas.util.Check.throwOrLogEx(Check.java:123)"
10: "	at de.metas.util.Check.assume(Check.java:170)"
11: "	at de.metas.util.Check.assumeNotEmpty(Check.java:366)"
12: "	at de.metas.util.Check.assumeNotEmpty(Check.java:339)"
13: "	at de.metas.handlingunits.picking.candidate.commands.ProcessHsAndPickingCandidateCommand.<init>(ProcessHsAndPickingCandidateCommand.java:92)"
14: "	at de.metas.handlingunits.picking.candidate.commands.ProcessHsAndPickingCandidateCommand.<init>(ProcessHsAndPickingCandidateCommand.java:69)"
15: "	at de.metas.handlingunits.picking.candidate.commands.ProcessHsAndPickingCandidateCommand$ProcessHsAndPickingCandidateCommandBuilder.build(ProcessHsAndPickingCandidateCommand.java:83)"
16: "	at de.metas.handlingunits.picking.PickingCandidateService.processForHUIds(PickingCandidateService.java:163)"
17: "	at de.metas.ui.web.picking.pickingslot.process.WEBUI_Picking_M_Picking_Candidate_Process.doIt(WEBUI_Picking_M_Picking_Candidate_Process.java:95)"
18: "	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:296)"
19: "	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:565)"
20: "	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:461)"
21: "	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:51)"
22: "	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:225)"
23: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
24: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
25: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
26: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
27: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
28: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
29: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)"
30: "	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:287)"
31: "	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:172)"
32: "	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:51)"
33: "	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:652)"
34: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:332)"
35: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:309)"
36: "	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:262)"
37: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
38: "	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:261)"
39: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
40: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
41: "	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:260)"
42: "	at sun.reflect.GeneratedMethodAccessor342.invoke(Unknown Source)"
43: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
44: "	at java.lang.reflect.Method.invoke(Method.java:498)"
45: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
46: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
47: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
48: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
49: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
50: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
51: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
52: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
53: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
54: "	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
55: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
56: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
57: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
58: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
59: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
60: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
61: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
62: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
63: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
64: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
65: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
66: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
67: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
68: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
69: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
70: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
71: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
72: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
73: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
74: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
75: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
76: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
77: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
78: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
79: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
80: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
81: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
82: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
83: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
84: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
85: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
86: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
87: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
88: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
89: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
90: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
91: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
92: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
93: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
94: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
95: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
96: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
97: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
98: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
99: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
[100 … 120]
100: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
101: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
102: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
103: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
104: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
105: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
106: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
107: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
108: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
109: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
110: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
111: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
112: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
113: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
114: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
115: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
116: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
117: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
118: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
119: "	at java.lang.Thread.run(Thread.java:748)"
120: ""
```

</details>

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Shall work,

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Process picking action: working correctly, picked HU is displayed read-only: OK
2. picked HU is not available for picking in HU editor anymore: OK
3. Qty picked is updated correctly,:
* in picking terminal: OK
* in shipment schedule: OK
4. picked HU is displayed correctly in the shipment schedule: OK
5. picked HU is displayed correctly in picking clearing, after processing (**not** before): OK
6. shipment is created with the qty from the picked HU: OK
7. picked HU is displayed correctly in the shipment, after it is created: OK
8. reactivating the processing action also worked fine (will test more in that area, in general regression testing for picking): OK

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh-webui-api/issues/1074 to `release`
