### ISSUE TITLE
Picking from source HU not working

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1082]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Picking from source HU is not working.
#### Which are the steps to reproduce?
1. Have a source HU for picking
2. Select a picking slot, and call `Pick to new HU`
3. Set a qty that is available in the source HU (or lower) in the modal window, OK:

<details>

```
{timestamp: 1540822428.166, status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
exception: "org.adempiere.exceptions.AdempiereException"
message: "Invalid quantity to pick: 0 Stk (source: 0 Stk)"
path: "/rest/api/process/ADP_540807/1000487/start"
status: 500
timestamp: 1540822428.166
trace: ["org.adempiere.exceptions.AdempiereException: Invalid quantity to pick: 0 Stk (source: 0 Stk)",…]
[0 … 99]
0: "org.adempiere.exceptions.AdempiereException: Invalid quantity to pick: 0 Stk (source: 0 Stk)"
1: "	at de.metas.handlingunits.picking.candidate.commands.PickHUCommand.performInTrx(PickHUCommand.java:97)"
2: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
3: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)"
4: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)"
5: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)"
6: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)"
7: "	at org.adempiere.ad.trx.api.ITrxManager.callInThreadInheritedTrx(ITrxManager.java:250)"
8: "	at de.metas.handlingunits.picking.candidate.commands.PickHUCommand.perform(PickHUCommand.java:89)"
9: "	at de.metas.handlingunits.picking.PickingCandidateService.pickHU(PickingCandidateService.java:93)"
10: "	at de.metas.ui.web.picking.pickingslot.process.WEBUI_Picking_PickQtyToNewHU.createAndAddHU(WEBUI_Picking_PickQtyToNewHU.java:171)"
11: "	at de.metas.ui.web.picking.pickingslot.process.WEBUI_Picking_PickQtyToNewHU.doIt(WEBUI_Picking_PickQtyToNewHU.java:124)"
12: "	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:296)"
13: "	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)"
14: "	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)"
15: "	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)"
16: "	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)"
17: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
18: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
19: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)"
20: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)"
21: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)"
22: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)"
23: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:507)"
24: "	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)"
25: "	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)"
26: "	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:50)"
27: "	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:651)"
28: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:333)"
29: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:310)"
30: "	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:262)"
31: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:420)"
32: "	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:261)"
33: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
34: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
35: "	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:260)"
36: "	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
37: "	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
38: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
39: "	at java.lang.reflect.Method.invoke(Method.java:498)"
40: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
41: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
42: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
43: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
44: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
45: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
46: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
47: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
48: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
49: "	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
50: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
51: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
52: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
53: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
54: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
55: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
56: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
57: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
58: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
59: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
60: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
61: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
62: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
63: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
64: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
65: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
66: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
67: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
68: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
69: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
70: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
71: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
72: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
73: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
74: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
75: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
76: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
77: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
78: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
79: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
80: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
81: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
82: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
83: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
84: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
85: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
86: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
87: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
88: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
89: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
90: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
91: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
92: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
93: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
94: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
95: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
96: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
97: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
98: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
99: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
[100 … 115]
100: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
101: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
102: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
103: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
104: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
105: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
106: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
107: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
108: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
109: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
110: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
111: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
112: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
113: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
114: "	at java.lang.Thread.run(Thread.java:748)"
115: ""
```

</details>

### What is the expected or desired behavior?
Shall work.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Picking from source HU:
* `Pick to new HU`working correctly: OK
* `Pick to existing HU`working correctly: OK
* `Move back to source HU`working correctly: OK
* processing picking: worked fine, correct qty from picking from source HU: OK
