### ISSUE TITLE
Cannot add orderline using Add new: CalloutExecutionException: datePromised

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1095]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you try to add an orderline for e.g. sales order using Add new, when trying to select the product, you get:

<details>

```
{timestamp: 1540910610.082, status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
exception: "org.adempiere.ad.callout.exceptions.CalloutExecutionException"
exceptionAttributes: {,…}
message: "datePromised"
path: "/rest/api/window/181/1000003/293/1000009"
status: 500
timestamp: 1540910610.082
trace: ["org.adempiere.ad.callout.exceptions.CalloutExecutionException: datePromised",…]
[0 … 99]
0: "org.adempiere.ad.callout.exceptions.CalloutExecutionException: datePromised"
1: "	at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:29)"
2: "	at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:26)"
3: "	at org.adempiere.ad.callout.annotations.api.impl.AnnotatedCalloutInstance.executePointcut(AnnotatedCalloutInstance.java:161)"
4: "	at org.adempiere.ad.callout.annotations.api.impl.AnnotatedCalloutInstance.execute(AnnotatedCalloutInstance.java:122)"
5: "	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:262)"
6: "	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:119)"
7: "	at de.metas.ui.web.window.model.Document.setValue(Document.java:1206)"
8: "	at de.metas.ui.web.window.model.Document.processValueChange(Document.java:1123)"
9: "	at de.metas.ui.web.window.model.Document.processValueChanges(Document.java:1138)"
10: "	at de.metas.ui.web.window.controller.WindowRestController.lambda$patchDocument0$6(WindowRestController.java:326)"
11: "	at de.metas.ui.web.window.model.DocumentCollection.lambda$forDocumentWritable$3(DocumentCollection.java:245)"
12: "	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentWritable(DocumentCollection.java:288)"
13: "	at de.metas.ui.web.window.model.DocumentCollection.forDocumentWritable(DocumentCollection.java:228)"
14: "	at de.metas.ui.web.window.controller.WindowRestController.patchDocument0(WindowRestController.java:322)"
15: "	at de.metas.ui.web.window.controller.WindowRestController.lambda$patchDocument$5(WindowRestController.java:316)"
16: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)"
17: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
18: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)"
19: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)"
20: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)"
21: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)"
22: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:499)"
23: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:476)"
24: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)"
25: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
26: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
27: "	at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)"
28: "	at de.metas.ui.web.window.controller.WindowRestController.patchDocument(WindowRestController.java:316)"
29: "	at de.metas.ui.web.window.controller.WindowRestController.patchIncludedDocument(WindowRestController.java:305)"
30: "	at sun.reflect.GeneratedMethodAccessor250.invoke(Unknown Source)"
31: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
32: "	at java.lang.reflect.Method.invoke(Method.java:498)"
33: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
34: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
35: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
36: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
37: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
38: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
39: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
40: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
41: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
42: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)"
43: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
44: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
45: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
46: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
47: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
48: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
49: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
50: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
51: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
52: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
53: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
54: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
55: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
56: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
57: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
58: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
59: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
60: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
61: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
62: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
63: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
64: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
65: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
66: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
67: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
68: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
69: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
70: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
71: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
72: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
73: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
74: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
75: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
76: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
77: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
78: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
79: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
80: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
81: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
82: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
83: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
84: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
85: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
86: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
87: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
88: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
89: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
90: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
91: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
92: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
93: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
94: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
95: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
96: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
97: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
98: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
99: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
[100 … 125]
100: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
101: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
102: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
103: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
104: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
105: "	at java.lang.Thread.run(Thread.java:748)"
106: "Caused by: java.lang.NullPointerException: datePromised"
107: "	at de.metas.order.OrderLine.<init>(OrderLine.java:44)"
108: "	at de.metas.order.OrderLine$OrderLineBuilder.build(OrderLine.java:44)"
109: "	at de.metas.order.OrderLineRepository.ofRecord(OrderLineRepository.java:81)"
110: "	at de.metas.order.OrderLineRepository$$FastClassBySpringCGLIB$$67a9a23f.invoke(<generated>)"
111: "	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)"
112: "	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)"
113: "	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)"
114: "	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)"
115: "	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)"
116: "	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)"
117: "	at de.metas.order.OrderLineRepository$$EnhancerBySpringCGLIB$$7b66aa40.ofRecord(<generated>)"
118: "	at de.metas.vertical.pharma.model.interceptor.C_OrderLine.validatePrescriptionProduct(C_OrderLine.java:82)"
119: "	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
120: "	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
121: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
122: "	at java.lang.reflect.Method.invoke(Method.java:498)"
123: "	at org.adempiere.ad.callout.annotations.api.impl.AnnotatedCalloutInstance.executePointcut(AnnotatedCalloutInstance.java:152)"
124: "	... 102 more"
125: ""
```
</details>

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by metas-dh** [comment]
update:
worked fine in this week's e2e, probably fixed in another task. closing this one.
