### ISSUE TITLE
"Issue only for what was received" method: Issued HUs remain issued and don't get destroyed

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1097]
### Is this a bug or feature request?
Bug?
### What is the current behavior?
When you have the "Issue only for what was received" method for a component, you do issueing after the product that is manufactured is received and the order is processed. 
Problem: 
* the HUs of the components with issue method "Backflush" were issued before the order was processed, and get destroyed in the processing: OK
* the HUs of the components with issue method "Issue only for what was received" remain "Issued" and don't get destroyed, bc the order is already processed, which leads to incorrect qties in stock: NOK
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
All issued HUs have to be destroyed after manufacturing is done, to be discussed how to do that for the HUs with ths particular issue method.

**Comment by teosarca** [comment]
update: If the PP_Order's Planning Status is Complete, then the issued materials will be automatically processed.

So, when the issue candidates are processed the HU is actually issued, so it gets empty, so it gets destroyed,

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. "Issue only for what was received" method: 
* Issued HUs get destroyed after being issued: OK
* new source HU can be selected if necessary: OK

2. "Backflush" method:
* Issued HUs don't get destroyed, remain issued: OK
* only get destroyed when order is processed: OK


Questions / problems:
* in case of "Issue only for what was received" method, the issued HU is directly destroyed and therefore cannot be removed anymore: @metas-mk @metasnw is that OK? 
* `Remove HU` is still available as action for the issued HU, although it is now destroyed: clicking it leads to:

<details>

```
{timestamp: 1541669377.58, status: 404, error: "Not Found",…}
error: "Not Found"
exception: "de.metas.ui.web.window.exceptions.DocumentNotFoundException"
message: "No document found for /W540189/1000154"
path: "/rest/api/process/ADP_540791"
status: 404
timestamp: 1541669377.58
trace: [,…]
[0 … 99]
0: "de.metas.ui.web.window.exceptions.DocumentNotFoundException: No document found for /W540189/1000154"
1: "	at de.metas.ui.web.window.model.DocumentCollection.retrieveRootDocumentFromRepository(DocumentCollection.java:356)"
2: "	at de.metas.ui.web.window.model.DocumentCollection.lambda$getOrLoadDocument$2(DocumentCollection.java:196)"
3: "	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)"
4: "	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)"
5: "	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)"
6: "	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)"
7: "	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)"
8: "	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)"
9: "	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)"
10: "	at de.metas.ui.web.window.model.DocumentCollection.getOrLoadDocument(DocumentCollection.java:194)"
11: "	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentReadonly(DocumentCollection.java:213)"
12: "	at de.metas.ui.web.window.model.DocumentCollection.forDocumentReadonly(DocumentCollection.java:171)"
13: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.createNewProcessInstance(ADProcessInstancesRepository.java:141)"
14: "	at de.metas.ui.web.process.ProcessRestController.lambda$createInstanceFromRequest$4(ProcessRestController.java:197)"
15: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)"
16: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
17: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)"
18: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)"
19: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)"
20: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)"
21: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:499)"
22: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:476)"
23: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)"
24: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
25: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
26: "	at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)"
27: "	at de.metas.ui.web.process.ProcessRestController.createInstanceFromRequest(ProcessRestController.java:196)"
28: "	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
29: "	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
30: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
31: "	at java.lang.reflect.Method.invoke(Method.java:498)"
32: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
33: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
34: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
35: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
36: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
37: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
38: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
39: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
40: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
41: "	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)"
42: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)"
43: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
44: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
45: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
46: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
47: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
48: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
49: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
50: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
51: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
52: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
53: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
54: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
55: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
56: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
57: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
58: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
59: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
60: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
61: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
62: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
63: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
64: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
65: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
66: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
67: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
68: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
69: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
70: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
71: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
72: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
73: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
74: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
75: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
76: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
77: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
78: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
79: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
80: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
81: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
82: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
83: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
84: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
85: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
86: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
87: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
88: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
89: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
90: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
91: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
92: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
93: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
94: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
95: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
96: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
97: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
98: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
99: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
[100 … 107]
100: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
101: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
102: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
103: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
104: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
105: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
106: "	at java.lang.Thread.run(Thread.java:748)"
107: ""

```

</details>


* could not issue less than suggested qty CU in `Issue CUs from source HUs` that is needed for the production, when i tried i got

<details>

```
{timestamp: 1541671574.38, status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
exception: "org.adempiere.exceptions.AdempiereException"
message: "Cannot fully unload all qty for AllocationRequest [product=P002738, qty=28886.00 mm (source: 28886.0000000000000000 mm), date=2018-11-08 00:00:00.0, fromTableRecord=null, forceQtyAllocation=true].↵Source: HUListAllocationSourceDestination{HUs Count=1, Current HU index=1, HUs=[X_M_HU[M_HU_ID=1000158, Value=1000158, trxName=<<ThreadInherited>>]]}↵Unload result: MutableAllocationResult [↵ qtyToAllocateInitial=28886.00↵ qtyToAllocate=8886.00↵ qtyAllocated=20000.00↵ transactions(1):↵	HUTransactionCandidate [product=ProductId(repoId=2005578), qty=-20000.00 mm (source: -20000.00 mm), date=2018-11-08 00:00:00.0, hu=1000158-No Packing Item, vhu=1000158-No Packing Item]↵ attribute transactions(0):↵]"
path: "/rest/api/process/ADP_540969/1004619/start"
status: 500
timestamp: 1541671574.38
trace: [,…]
[0 … 99]
0: "org.adempiere.exceptions.AdempiereException: Cannot fully unload all qty for AllocationRequest [product=P002738, qty=28886.00 mm (source: 28886.0000000000000000 mm), date=2018-11-08 00:00:00.0, fromTableRecord=null, forceQtyAllocation=true]."
1: "Source: HUListAllocationSourceDestination{HUs Count=1, Current HU index=1, HUs=[X_M_HU[M_HU_ID=1000158, Value=1000158, trxName=<<ThreadInherited>>]]}"
2: "Unload result: MutableAllocationResult ["
3: " qtyToAllocateInitial=28886.00"
4: " qtyToAllocate=8886.00"
5: " qtyAllocated=20000.00"
6: " transactions(1):"
7: "	HUTransactionCandidate [product=ProductId(repoId=2005578), qty=-20000.00 mm (source: -20000.00 mm), date=2018-11-08 00:00:00.0, hu=1000158-No Packing Item, vhu=1000158-No Packing Item]"
8: " attribute transactions(0):"
9: "]"
10: "	at de.metas.handlingunits.allocation.impl.HULoader.unloadSourceThenLoadDestination(HULoader.java:272)"
11: "	at de.metas.handlingunits.allocation.impl.HULoader.lambda$load$0(HULoader.java:185)"
12: "	at de.metas.handlingunits.allocation.impl.HUContextProcessorExecutor$1.run(HUContextProcessorExecutor.java:102)"
13: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
14: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
15: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)"
16: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)"
17: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)"
18: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)"
19: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:507)"
20: "	at de.metas.handlingunits.allocation.impl.HUContextProcessorExecutor.run(HUContextProcessorExecutor.java:79)"
21: "	at de.metas.handlingunits.allocation.impl.HULoader.processInHUContext(HULoader.java:204)"
22: "	at de.metas.handlingunits.allocation.impl.HULoader.load(HULoader.java:178)"
23: "	at de.metas.handlingunits.pporder.api.HUPPOrderIssueReceiptCandidatesProcessor.processIssueCandidate(HUPPOrderIssueReceiptCandidatesProcessor.java:296)"
24: "	at de.metas.handlingunits.pporder.api.HUPPOrderIssueReceiptCandidatesProcessor.processCandidate(HUPPOrderIssueReceiptCandidatesProcessor.java:167)"
25: "	at de.metas.handlingunits.pporder.api.HUPPOrderIssueReceiptCandidatesProcessor.lambda$process$0(HUPPOrderIssueReceiptCandidatesProcessor.java:139)"
26: "	at org.adempiere.ad.trx.processor.api.ITrxItemExecutorBuilder$1.process(ITrxItemExecutorBuilder.java:125)"
27: "	at org.adempiere.ad.trx.processor.api.impl.TrxItemProcessor2TrxItemChunkProcessorWrapper.process(TrxItemProcessor2TrxItemChunkProcessorWrapper.java:76)"
28: "	at org.adempiere.ad.trx.processor.api.impl.TrxItemChunkProcessorExecutor.processItem(TrxItemChunkProcessorExecutor.java:260)"
29: "	at org.adempiere.ad.trx.processor.api.impl.TrxItemChunkProcessorExecutor.execute(TrxItemChunkProcessorExecutor.java:157)"
30: "	at org.adempiere.ad.trx.processor.api.impl.TrxItemExecutorBuilder.process(TrxItemExecutorBuilder.java:76)"
31: "	at org.adempiere.ad.trx.processor.api.ITrxItemExecutorBuilder.process(ITrxItemExecutorBuilder.java:95)"
32: "	at de.metas.handlingunits.pporder.api.HUPPOrderIssueReceiptCandidatesProcessor.process(HUPPOrderIssueReceiptCandidatesProcessor.java:146)"
33: "	at de.metas.handlingunits.pporder.api.impl.HUPPOrderIssueProducer.createIssues(HUPPOrderIssueProducer.java:123)"
34: "	at de.metas.ui.web.pporder.process.WEBUI_PP_Order_M_Source_HU_IssueCUQty.doIt(WEBUI_PP_Order_M_Source_HU_IssueCUQty.java:134)"
35: "	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:296)"
36: "	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)"
37: "	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)"
38: "	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)"
39: "	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)"
40: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
41: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
42: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)"
43: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)"
44: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)"
45: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)"
46: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:507)"
47: "	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)"
48: "	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)"
49: "	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:50)"
50: "	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:651)"
51: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:333)"
52: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:310)"
53: "	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:262)"
54: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:420)"
55: "	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:261)"
56: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
57: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
58: "	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:260)"
59: "	at sun.reflect.GeneratedMethodAccessor286.invoke(Unknown Source)"
60: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
61: "	at java.lang.reflect.Method.invoke(Method.java:498)"
62: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
63: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
64: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
65: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
66: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
67: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
68: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
69: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
70: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
71: "	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
72: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
73: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
74: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
75: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
76: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
77: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
78: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
79: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
80: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
81: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
82: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
83: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
84: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
85: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
86: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
87: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
88: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
89: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
90: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
91: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
92: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
93: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
94: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
95: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
96: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
97: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
98: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
99: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
[100 … 137]
100: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
101: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
102: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
103: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
104: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
105: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
106: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
107: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
108: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
109: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
110: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
111: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
112: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
113: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
114: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
115: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
116: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
117: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
118: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
119: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
120: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
121: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
122: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
123: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
124: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
125: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
126: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
127: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
128: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
129: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
130: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
131: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
132: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
133: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
134: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
135: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
136: "	at java.lang.Thread.run(Thread.java:748)"
137: ""

```

</details>

=> not sure this is realistic or if the qty needed for manufacturing will always be issued? @metasnw  wdyt?

**Comment by metasnw** [comment]
reg 1) 
that is fine in my opinion. we can make it more flexible later

reg 2) and 3) 
in my opinion those are NOKs that will hit us. we should fix them

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

retested testcase above:
2) `Remove HU` is still available as action for the issued HU: afaiu OK, clicking it results in error with proper msg for the user: "Cannot reverse candidate because it's already processed": OK

3)  issueing less than suggested qty CU in `Issue CUs from source HUs` that is needed for the production working correctly:
* the qty CU that was manually set is issued and destroyed: OK
* when using `Issue CUs from source HUs` again the suggested qty CU is the qty CU needed - qty CU already issued: OK

=> rest worked fine as before (issue bethod Backflush etc.)

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh-webui-api/issues/1097 to `release`
