### ISSUE TITLE
Generate PO from Sales order not working anymore

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1113]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When trying to run `Generate PO from Sales order` you get

<details>

```
{timestamp: 1543242598.178, status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
exception: "de.metas.ui.web.process.exceptions.ProcessExecutionException"
message: "Mandatory field DatePromised_From not filled"
path: "/rest/api/process/ADP_193/1000690/start"
status: 500
timestamp: 1543242598.178
trace: [,…]
0: "de.metas.ui.web.process.exceptions.ProcessExecutionException: Mandatory field DatePromised_From not filled"
1: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.saveIfValidAndHasChanges(ADProcessInstanceController.java:353)"
2: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:303)"
3: "	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:262)"
4: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:420)"
5: "	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:261)"
6: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
7: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
8: "	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:260)"
9: "	at sun.reflect.GeneratedMethodAccessor360.invoke(Unknown Source)"
10: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
11: "	at java.lang.reflect.Method.invoke(Method.java:498)"
12: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
13: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
14: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
15: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
16: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
17: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
18: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
19: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
20: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
21: "	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
22: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
23: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
24: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
25: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
26: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
27: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
28: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
29: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
30: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
31: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
32: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
33: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
34: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
35: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
36: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
37: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
38: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
39: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
40: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
41: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
42: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
43: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
44: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
45: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
46: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
47: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
48: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
49: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
50: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
51: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
52: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
53: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
54: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
55: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
56: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
57: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
58: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
59: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
60: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
61: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
62: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
63: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
64: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
65: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
66: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
67: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
68: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
69: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
70: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
71: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
72: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
73: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
74: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
75: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
76: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
77: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
78: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
79: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
80: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
81: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
82: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
83: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
84: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
85: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
86: "	at java.lang.Thread.run(Thread.java:748)"
87: ""
```

</details>

#### Which are the steps to reproduce?
1. Have a vendor for a product that is on both sales and purchase pricelist
2. Create sales order for that product
3. Run action `Generate PO from Sales order` (with only the sales order no. as param set): => error, NOK

=> works fine in Swing

### What is the expected or desired behavior?
Should work

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* Generate PO from Sales order: no errors when running the action: OK
* purchase order is created correctly: 
    * correct vendor, correct product qty, correct price: OK
    * reference: sales order doc no.: OK
    * status draft: OK
