### ISSUE TITLE
Error when trying to transform CU on standalone TU 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1184]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you select a CU on a standalone TU and call the `Transfrom` action, you get

<details/>
```
{timestamp: 1554186622.382, status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
exception: "org.adempiere.exceptions.AdempiereException"
message: "Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
↵Bitte leiten Sie diese Meldung an metas weiter:↵↵Assumption failure: paramsIn not empty"
path: "/rest/api/process/ADP_540763"
status: 500
timestamp: 1554186622.382
trace: [,…]
[0 … 99]
0: "org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
"
1: "Bitte leiten Sie diese Meldung an metas weiter:"
2: ""
3: "Assumption failure: paramsIn not empty"
4: "	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
5: "	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
6: "	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)"
7: "	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)"
8: "	at de.metas.util.Check.mkEx(Check.java:115)"
9: "	at de.metas.util.Check.throwOrLogEx(Check.java:130)"
10: "	at de.metas.util.Check.assume(Check.java:182)"
11: "	at de.metas.util.Check.assumeNotEmpty(Check.java:377)"
12: "	at de.metas.util.Check.assumeNotEmpty(Check.java:350)"
13: "	at org.compiere.util.DB.buildSqlList(DB.java:2366)"
14: "	at de.metas.ui.web.view.descriptor.SqlViewKeyColumnNamesMap.getSqlFilterByRowIds(SqlViewKeyColumnNamesMap.java:312)"
15: "	at de.metas.ui.web.view.descriptor.SqlViewKeyColumnNamesMap.access$200(SqlViewKeyColumnNamesMap.java:59)"
16: "	at de.metas.ui.web.view.descriptor.SqlViewKeyColumnNamesMap$SqlFilterByRowIdsBuilder.build(SqlViewKeyColumnNamesMap.java:292)"
17: "	at de.metas.ui.web.view.descriptor.SqlViewSelectionQueryBuilder.buildSqlWhereClause(SqlViewSelectionQueryBuilder.java:669)"
18: "	at de.metas.ui.web.view.descriptor.SqlViewSelectionQueryBuilder.access$000(SqlViewSelectionQueryBuilder.java:76)"
19: "	at de.metas.ui.web.view.descriptor.SqlViewSelectionQueryBuilder$SqlWhereClauseBuilder.build(SqlViewSelectionQueryBuilder.java:638)"
20: "	at de.metas.ui.web.handlingunits.SqlHUEditorViewRepository.buildSqlWhereClause(SqlHUEditorViewRepository.java:660)"
21: "	at de.metas.ui.web.handlingunits.HUEditorViewBuffer_HighVolume.getSqlWhereClause(HUEditorViewBuffer_HighVolume.java:310)"
22: "	at de.metas.ui.web.handlingunits.HUEditorView.getSqlWhereClause(HUEditorView.java:283)"
23: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.createProcessInfo(ADProcessInstancesRepository.java:248)"
24: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.createNewProcessInstance0(ADProcessInstancesRepository.java:162)"
25: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.lambda$createNewProcessInstance$0(ADProcessInstancesRepository.java:141)"
26: "	at de.metas.ui.web.window.model.DocumentCollection.lambda$forDocumentReadonly$1(DocumentCollection.java:188)"
27: "	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentReadonly(DocumentCollection.java:232)"
28: "	at de.metas.ui.web.window.model.DocumentCollection.forDocumentReadonly(DocumentCollection.java:185)"
29: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.createNewProcessInstance(ADProcessInstancesRepository.java:141)"
30: "	at de.metas.ui.web.process.ProcessRestController.lambda$createInstanceFromRequest$3(ProcessRestController.java:194)"
31: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)"
32: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
33: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)"
34: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)"
35: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)"
36: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)"
37: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:499)"
38: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:476)"
39: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)"
40: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
41: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
42: "	at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)"
43: "	at de.metas.ui.web.process.ProcessRestController.createInstanceFromRequest(ProcessRestController.java:193)"
44: "	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
45: "	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
46: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
47: "	at java.lang.reflect.Method.invoke(Method.java:498)"
48: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
49: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
50: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
51: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
52: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
53: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
54: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
55: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
56: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
57: "	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)"
58: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)"
59: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
60: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
61: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
62: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
63: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
64: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
65: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
66: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
67: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
68: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
69: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
70: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
71: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
72: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
73: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
74: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
75: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
76: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
77: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
78: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
79: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
80: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
81: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
82: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
83: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
84: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
85: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
86: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
87: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
88: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
89: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
90: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
91: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
92: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
93: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
94: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
95: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
96: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
97: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
98: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
99: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
[100 … 123]
100: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
101: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
102: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
103: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
104: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
105: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
106: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
107: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
108: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
109: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
110: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
111: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
112: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
113: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
114: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
115: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
116: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
117: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
118: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
119: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
120: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
121: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
122: "	at java.lang.Thread.run(Thread.java:748)"
123: ""
```
</details>

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by teosarca** [comment]
might be already solved by https://github.com/metasfresh/metasfresh-webui-api/issues/1206

**Comment by teosarca** [comment]
closing legacy issue
