### ISSUE TITLE
make error message more clear when printing in receipt candidates

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#325]
### Is this a bug or feature request?
feature
### What is the current behavior?
message for Drucken Produktanlieferung when the config is missing is a bit unclear
#### Which are the steps to reproduce?
go to Material Receipt Candidates and select Drucken Produktanlieferung
=> 
Process error
Failed printing ProcessInfo{title=Wareneingang POS (Jasper), AD_Process_ID=540491, AD_PInstance_ID=1358188, AD_Table_ID=260, Record_ID=1006457, Classname=org.compiere.report.ReportStarter, reportTemplate=Prefixde/metas/docs/purchase/inout/pos_report.jasper, reportLanguage=Language{name=Deutsch (Schweiz), AD_Language=de_CH, locale=de_CH, decimalPoint=false}}
### What is the expected or desired behavior?
would be nice to have the reason why it failed (like which config is missing)

**Comment by teosarca** [comment]
server stacktrace is:
```
rg.adempiere.exceptions.AdempiereException: Failed printing ProcessInfo{title=Wareneingang POS (Jasper), AD_Process_ID=540491, AD_PInstance_ID=1363562, AD_Table_ID=260, Record_ID=1006469, Classname=org.compiere.report.ReportStarter, reportTemplate=@PREFIX@de/metas/docs/purchase/inout/pos_report.jasper, reportLanguage=Language{name=Deutsch, AD_Language=de_DE, locale=de_DE, decimalPoint=false}}
        at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:85)
        at org.compiere.report.ReportStarter.startProcess0(ReportStarter.java:236)
        at org.compiere.report.ReportStarter.startProcess(ReportStarter.java:76)
        at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:557)
        at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:453)
        at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:49)
        at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:219)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:500)
        at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:279)
        at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:167)
        at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:49)
        at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:647)
        at de.metas.handlingunits.report.HUReceiptScheduleReportExecutor.executeHUReport(HUReceiptScheduleReportExecutor.java:148)
        at de.metas.ui.web.handlingunits.process.WEBUI_M_ReceiptSchedule_RunMaterialReceiptJasper.doIt(WEBUI_M_ReceiptSchedule_RunMaterialReceiptJasper.java:68)
        at de.metas.process.JavaProcess.startProcess(JavaProcess.java:271)
        at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:557)
        at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:453)
        at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:49)
        at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:219)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:500)
        at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:279)
        at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:167)
        at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:49)
        at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:647)
        at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:287)
        at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:262)
        at de.metas.ui.web.process.ProcessRestController.lambda$null$7(ProcessRestController.java:207)
        at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:336)
        at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$8(ProcessRestController.java:206)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)
        at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:205)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:121)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:164)
        at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:107)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed printing ProcessInfo{title=Wareneingang POS (Jasper), AD_Process_ID=540491, AD_PInstance_ID=1363562, AD_Table_ID=260, Record_ID=1006469, Classname=org.compiere.report.ReportStarter, reportTemplate=@PREFIX@de/metas/docs/purchase/inout/pos_report.jasper, reportLanguage=Language{name=Deutsch, AD_Language=de_DE, locale=de_DE, decimalPoint=false}}
        at org.compiere.report.impl.JasperService.print(JasperService.java:123)
        at org.compiere.report.ReportStarter.startProcessDirectPrint(ReportStarter.java:107)
        at org.compiere.report.ReportStarter.startProcess0(ReportStarter.java:232)
        ... 150 common frames omitted
Caused by: org.adempiere.exceptions.AdempiereException: java.awt.print.PrinterException: Not a 2D print service: IPP Printer : null
PrintServiceName=null
        at org.compiere.report.impl.JasperService.setupAndPrint(JasperService.java:166)
        at org.compiere.report.impl.JasperService.print(JasperService.java:88)
        ... 152 common frames omitted
Caused by: net.sf.jasperreports.engine.JRException: java.awt.print.PrinterException: Not a 2D print service: IPP Printer : null
        at net.sf.jasperreports.engine.export.JRPrintServiceExporter.exportReport(JRPrintServiceExporter.java:334)
        at org.compiere.report.impl.JasperService.setupAndPrint(JasperService.java:156)
        ... 153 common frames omitted
Caused by: java.awt.print.PrinterException: Not a 2D print service: IPP Printer : null
        at sun.print.RasterPrinterJob.setPrintService(RasterPrinterJob.java:535)
        at net.sf.jasperreports.engine.export.JRPrintServiceExporter.exportReport(JRPrintServiceExporter.java:330)
        ... 154 common frames omitted

```

**Comment by metas-lc** [comment]
IT 
go to Material Receipt Candidates and select Drucken Produktanlieferung
=>
java.awt.print.PrinterException: Not a 2D print service: 
IPP Printer : null 
PrintServiceName=null
