### ISSUE TITLE
ZoomInto not working for string lookups

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#417]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* Open Mandant/Client: https://w101.metasfresh.com:8443/window/109/1000000
* click on Language label to zoom into
![image](https://cloud.githubusercontent.com/assets/1244701/26510066/23cd6808-4264-11e7-924d-89a5ca87da76.png)

#### Stacktrace
```
org.adempiere.exceptions.AdempiereException: Failed converting AD_Language's value 'StringLookupValue{id=de_DE, displayName=trl{trls={en_US=Deutsch (Deutschland)}, default=Deutsch (Deutschland)}}' (class de.metas.ui.web.window.datatypes.LookupValue$StringLookupValue) to interface org.adempiere.util.lang.ITableRecordReference
 LookupDataSource: LookupDataSourceAdapter{Cached{GenericSqlLookupDataSourceFetcher{lookupTableName=AD_Language, sqlForFetchingExpression=Cached{AccessSql{AD_Language, FQ, Composite{
* SELECT NULL,AD_Language.AD_Language,NULLIF (TRIM(AD_Language.Name), ''),AD_Language.IsActive FROM AD_Language
 WHERE
 /* lookup where clause */ ((AD_Language.IsSystemLanguage='Y' OR AD_Language.IsBaseLanguage='Y'))
 AND  /* filter */ unaccent_string(NULLIF (TRIM(AD_Language.Name), ''), 1) ILIKE unaccent_string(
* @FilterSql@
* , 1)
 AND  /* active */ ('
* @SqlShowInactive/N@
* '='Y' OR AD_Language.IsActive='Y')
 ORDER BY 3
 OFFSET
* @Offset/0@
*
 LIMIT
* @Limit/1000@}}}, postQueryPredicate=NULL}}}
 Widget type: null
        at de.metas.ui.web.window.descriptor.DocumentFieldDescriptor.convertToValueClass(DocumentFieldDescriptor.java:600)
        at de.metas.ui.web.window.descriptor.DocumentFieldDescriptor.convertToValueClass(DocumentFieldDescriptor.java:349)
        at de.metas.ui.web.window.model.DocumentField.convertToValueClass(DocumentField.java:328)
        at de.metas.ui.web.window.model.DocumentField.getValueAs(DocumentField.java:269)
        at de.metas.ui.web.window.controller.WindowRestController.lambda$getDocumentFieldZoomInto$10(WindowRestController.java:532)
        at de.metas.ui.web.window.model.DocumentCollection.lambda$forDocumentReadonly$0(DocumentCollection.java:113)
        at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentReadonly(DocumentCollection.java:150)
        at de.metas.ui.web.window.model.DocumentCollection.forDocumentReadonly(DocumentCollection.java:110)
        at de.metas.ui.web.window.controller.WindowRestController.getDocumentFieldZoomInto(WindowRestController.java:498)
        at de.metas.ui.web.window.controller.WindowRestController.getDocumentFieldZoomInto(WindowRestController.java:475)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
```

**Comment by teosarca** [comment]
Update: disabled in #418 until we fix it.
