### ISSUE TITLE
Cannot open the menu when logged in as System Administrator

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#446]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* login with SuperUser and role System Administrator
* try to open the menu and you will get
```
org.adempiere.exceptions.AdempiereException: AD_Menu_ID not set
        at de.metas.ui.web.menu.MenuNode$Builder.getAD_Menu_ID(MenuNode.java:359)
        at de.metas.ui.web.menu.MenuNode$Builder.getId(MenuNode.java:366)
        at de.metas.ui.web.menu.MenuNode$Builder.access$100(MenuNode.java:327)
        at de.metas.ui.web.menu.MenuNode.<init>(MenuNode.java:89)
        at de.metas.ui.web.menu.MenuNode.<init>(MenuNode.java:42)
        at de.metas.ui.web.menu.MenuNode$Builder.build(MenuNode.java:346)
        at de.metas.ui.web.menu.MenuTreeLoader.createMenuNodeRecursivelly(MenuTreeLoader.java:142)
        at de.metas.ui.web.menu.MenuTreeLoader.load(MenuTreeLoader.java:100)
        at de.metas.ui.web.menu.MenuTreeRepository$1.load(MenuTreeRepository.java:64)
        at de.metas.ui.web.menu.MenuTreeRepository$1.load(MenuTreeRepository.java:59)
```

### What is the expected or desired behavior?
Menu shall be rendered correctly.

**Comment by metas-lc** [comment]
IT
login with SuperUser and role System Administrator, open the Menu => works with no errors
also browsed a little => works fine, no errors
