### ISSUE TITLE
Can not add attribute to attribute set 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#454]
### Is this a bug or feature request?
bug

### What is the current behavior?
can not add a line which is saved

#### Which are the steps to reproduce?
try to add via add new in:
https://w101.metasfresh.com:8443/window/256/1000012

![image](https://user-images.githubusercontent.com/16079655/27036627-c05c3536-4f85-11e7-96c2-54f431e4fbd2.png)

### What is the expected or desired behavior?
line should be saved

**Comment by teosarca** [comment]
update: basically it's because M_AttributeUse does not have a single PK.

**Comment by teosarca** [comment]
stack trace
```
2017-06-13 12:17:56.128 ERROR 4327 [                ][          ] --- [http-nio-8080-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.adempiere.exceptions.AdempiereException: Failed building where clause because there is no Key Column defined in SqlDocumentEntityDataBindingDescriptor{sqlTableName=M_AttributeUse, sqlTableAlias=d1}] with root cause

org.adempiere.exceptions.AdempiereException: Failed building where clause because there is no Key Column defined in SqlDocumentEntityDataBindingDescriptor{sqlTableName=M_AttributeUse, sqlTableAlias=d1}
        at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.buildSqlWhereClause(SqlDocumentQueryBuilder.java:395)
        at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.getSqlWhereAndParams(SqlDocumentQueryBuilder.java:361)
        at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.buildSql(SqlDocumentQueryBuilder.java:298)
        at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.getSqlAndParams(SqlDocumentQueryBuilder.java:278)
        at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.getSql(SqlDocumentQueryBuilder.java:265)
        at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.retriveDocuments(SqlDocumentsRepository.java:165)
        at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.retrieveDocument(SqlDocumentsRepository.java:250)
        at de.metas.ui.web.window.model.DocumentQuery$Builder.retriveDocumentOrNull(DocumentQuery.java:196)
        at de.metas.ui.web.window.model.HighVolumeReadWriteIncludedDocumentsCollection.getDocumentById(HighVolumeReadWriteIncludedDocumentsCollection.java:199)
        at de.metas.ui.web.window.model.Document.getIncludedDocument(Document.java:1499)
        at de.metas.ui.web.window.model.DocumentCollection.lambda$forDocumentReadonly$0(DocumentCollection.java:117)
        at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentReadonly(DocumentCollection.java:150)
        at de.metas.ui.web.window.model.DocumentCollection.forDocumentReadonly(DocumentCollection.java:110)
        at de.metas.ui.web.window.controller.WindowRestController.getDocumentFieldDropdown(WindowRestController.java:473)
        at de.metas.ui.web.window.controller.WindowRestController.getDocumentFieldDropdown(WindowRestController.java:465)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
```

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* I was able to both " add new"  and delete attributes in Attribute set.
