### ISSUE TITLE
cannot create invoice from multiple candidates of inventory

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#500]
### Is this a bug or feature request?
bug
### What is the current behavior?
cannot create invoice from multiple candidates of inventory => error
#### Which are the steps to reproduce?
1. create 1 purchase order with 2 products. 
2. Open both of them in material receipt candidates - hu editor. (don't transform. Create 1 inout for both products), then, right away, create disposal
3. go to invoice candidates of the disposa, select both of them, create invoice =>

"org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "master"↵  Position: 452↵	SQL: INSERT INTO T_SELECTION(AD_PINSTANCE_ID, T_SELECTION_ID)  SELECT 1005908, C_Invoice_Candidate_ID FROM C_Invoice_Candidate↵ WHERE ((((/* MQuery-e4dc650c-bec6-41cb-8629-7b65095fe752 */((↵	↵exists (↵	select 1 from M_Inventory i↵	join M_InventoryLine il on i.M_Inventory_ID = il.M_Inventory_ID↵	join C_Invoice_Candidate ic on ic.AD_Table_ID = get_table_ID('M_InventoryLine') and ic.Record_ID =  il.M_InventoryLine_ID ↵	↵	where ic.C_Invoice_Candidate_ID = master.C_Invoice_Candidate_ID and i.M_Inventory_ID = 1000007↵	)))) AND (exists (select 1 from T_WEBUI_ViewSelection sel  where  UUID='540092-1622cb35678c4d04be31e05febb16840' and sel.Record_ID=C_Invoice_Candidate.C_Invoice_Candidate_ID) AND C_Invoice_Candidate.C_Invoice_Candidate_ID IN (1000102,1000101))) AND (AD_Client_ID=1000000) AND (1=1)) AND (IsActive=?) AND (AD_Client_ID=?))  AND ↵ /* security-client */ C_Invoice_Candidate.AD_Client_ID IN (0,1000000)↵ /* security-record */ AND C_Invoice_Candidate.C_Invoice_Candidate_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 540270 AND AD_User_ID <> 2188224 AND IsActive = 'Y' )↵	SQL params: [true, 1000000]"
### What is the expected or desired behavior?
should not get error. Invoice should generate

**Comment by teosarca** [comment]
stack trace:
```
org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "master"
  Position: 452
        SQL: INSERT INTO T_SELECTION(AD_PINSTANCE_ID, T_SELECTION_ID)  SELECT 1489996, C_Invoice_Candidate_ID FROM C_Invoice_Candidate
 WHERE ((((/* MQuery-c9189879-57f6-4eeb-b572-e39d3c6b7f3c */((

exists (
        select 1 from M_Inventory i
        join M_InventoryLine il on i.M_Inventory_ID = il.M_Inventory_ID
        join C_Invoice_Candidate ic on ic.AD_Table_ID = get_table_ID('M_InventoryLine') and ic.Record_ID =  il.M_InventoryLine_ID

        where ic.C_Invoice_Candidate_ID = master.C_Invoice_Candidate_ID and i.M_Inventory_ID = 1000065
        )))) AND (exists (select 1 from T_WEBUI_ViewSelection sel  where  UUID='540092-194133ef2581489a9983c6e8ae5b8bcf' and sel.Record_ID=C_Invoice_Candidate.C_Invoice_Candidate_ID) AND C_
Invoice_Candidate.C_Invoice_Candidate_ID IN (1003642,1003643))) AND (AD_Client_ID=1000000) AND (1=1)) AND (IsActive=?) AND (AD_Client_ID=?))  AND
 /* security-client */ C_Invoice_Candidate.AD_Client_ID IN (0,1000000)
 /* security-record */ AND C_Invoice_Candidate.C_Invoice_Candidate_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 540270 AND AD_User_ID <> 2188223 AND IsActive = 'Y
' )
        SQL params: [true, 1000000]
        at org.adempiere.exceptions.DBException.wrapIfNeeded(DBException.java:88)
        at org.compiere.util.DB.executeUpdate(DB.java:990)
        at org.compiere.util.DB.executeUpdateEx(DB.java:1040)
        at org.compiere.util.DB.executeUpdateEx(DB.java:1023)
        at org.adempiere.ad.dao.impl.TypedSqlQuery.createSelection(TypedSqlQuery.java:1567)
        at de.metas.invoicecandidate.process.C_Invoice_Candidate_EnqueueSelection.createSelection(C_Invoice_Candidate_EnqueueSelection.java:166)
        at de.metas.invoicecandidate.process.C_Invoice_Candidate_EnqueueSelection.prepare(C_Invoice_Candidate_EnqueueSelection.java:86)
        at de.metas.process.JavaProcess.prepareProcess(JavaProcess.java:622)
        at de.metas.process.JavaProcess.startProcess(JavaProcess.java:242)
        at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:557)
        at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:453)
        at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:49)
        at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:219)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.runOutOfTransaction(AbstractTrxManager.java:923)
        at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:275)
        at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:167)
        at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:49)
        at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:647)
        at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:283)
        at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:257)
        at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:249)
        at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:360)
        at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:248)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)
        at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:246)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
