### ISSUE TITLE
Error when opening MRP Product Info

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-api#515]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* When opening MRP Product Info from the webui, I get this error: 

>App.js:83 org.postgresql.util.PSQLException: ERROR: column "record_id" is of type numeric but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 119
	SQL: INSERT INTO T_WEBUI_ViewSelection ( UUID, Line, Record_ID)
 SELECT 
  ?
, row_number() OVER (ORDER BY (Value) ASC)
, Value
 FROM X_MRP_ProductInfo_V master
 WHERE 1=1   AND 
 /* security-client */ master.AD_Client_ID IN (0,1000000)
 LIMIT ?
	SQL params: [540338-7188e940e5864b6aa86c21aab9a29a68, 2000]

![image](https://user-images.githubusercontent.com/16001442/28467986-4c5f0ea0-6e3a-11e7-9c9a-1907d0cfe501.png)

#### Which are the steps to reproduce?
* Just open MRP Product Info from webui.

### What is the expected or desired behavior?
* THere should be no error.

**Comment by teosarca** [comment]
Cannot reproduce locally because i cannot find the AD_Window_ID=540338
i.e. following SQL returns nothing
```
select * from AD_Window where AD_Window_ID=540338
```

Have u commited all the migration scripts or is the MRP Product Info integrated to master?

**Comment by teosarca** [comment]
but anyways, the X_MRP_ProductInfo_V.Value, which for some reason is considered the key, is a string column while T_WEBUI_ViewSelection.Record_ID is numeric.


Failing stacktrace is:
```
2017-07-22 20:03:23.520  WARN 27177 [ 0:0:0:0:0:0:0:1][       teo] --- [http-nio-8080-exec-14] d.m.ui.web.config.WebuiExceptionHandler  : Got REST exception from handler=public de.metas.ui.web.view.json.JSONViewResult de.metas.ui.web.view.ViewRestController.createView(java.lang.String,de.metas.ui.web.view.json.JSONCreateViewRequest)

org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "record_id" is of type numeric but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 119
        SQL: INSERT INTO T_WEBUI_ViewSelection ( UUID, Line, Record_ID)
 SELECT
  ?
, row_number() OVER (ORDER BY (Value) ASC)
, Value
 FROM X_MRP_ProductInfo_V master
 WHERE 1=1   AND
 /* security-client */ master.AD_Client_ID IN (0,1000000)
 LIMIT ?
        SQL params: [540338-455d58fb5cca44b6a2ed4d8826146b8d, 2000]
        at org.adempiere.exceptions.DBException.wrapIfNeeded(DBException.java:88)
        at org.compiere.util.DB.executeUpdate(DB.java:990)
        at org.compiere.util.DB.executeUpdateEx(DB.java:1040)
        at org.compiere.util.DB.executeUpdateEx(DB.java:1023)
        at de.metas.ui.web.view.SqlViewRowIdsOrderedSelectionFactory.createOrderedSelection(SqlViewRowIdsOrderedSelectionFactory.java:111)
        at de.metas.ui.web.view.SqlViewDataRepository.createOrderedSelection(SqlViewDataRepository.java:171)
        at de.metas.ui.web.view.DefaultView.<init>(DefaultView.java:123)
        at de.metas.ui.web.view.DefaultView.<init>(DefaultView.java:69)
        at de.metas.ui.web.view.DefaultView$Builder.build(DefaultView.java:449)
        at de.metas.ui.web.view.SqlViewFactory.createView(SqlViewFactory.java:136)
        at de.metas.ui.web.view.ViewsRepository.createView(ViewsRepository.java:235)
        at sun.reflect.GeneratedMethodAccessor266.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy145.createView(Unknown Source)
        at de.metas.ui.web.view.ViewRestController.createView(ViewRestController.java:119)
        at sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source)
...
```
