### ISSUE TITLE
Unable to see list of document's attachments

### ISSUE THREAD

**Issue by wiadev** [metasfresh/metasfresh-webui-api#532]
### Type of issue
Bug 

### Steps to reproduce:

1. Open window/123/2156482. This document has many attachments uploaded
2. Click on dropdown menu button (in top-right corner of the page)
3. Then click on tab with paperclip icon
4. Loading indicator will appear, need to wait some 20-30 seconds and then it throws the error

You'll get following error:

Error: Error while loading model...
Server error
Error while loading model from ResultSet Name der DB-Tabelle: AD_AttachmentEntry Class: class org.compiere.model.X_AD_AttachmentEntry

![screenshot at aug 07 20-52-29](https://user-images.githubusercontent.com/18234060/29041227-7a9e0fe8-7bb2-11e7-86ea-5dfe5260ec5b.png)

**Comment by metasnw** [comment]
```
found this in server log:

2017-08-07 20:49:14.451  WARN 29565 [ 173.245.219.129][    wiadev] --- [http-nio-8080-exec-6] d.m.ui.web.config.WebuiExceptionHandler  : Got REST exception from handler=public java.util.List<de.metas.ui.web.attachments.json.JSONAttachment> de.metas.ui.web.attachments.DocumentAttachmentsRestController.getAttachments(java.lang.String,java.lang.String)

org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: Ran out of memory retrieving query results.
        SQL: SELECT AD_AttachmentEntry_ID,AD_Attachment_ID,AD_Client_ID,AD_Org_ID,AD_Table_ID,BinaryData,ContentType,Created,CreatedBy,Description,FileName,IsActive,Record_ID,Updated,UpdatedBy
 FROM AD_AttachmentEntry
 WHERE ((AD_Attachment_ID = ?))
 ORDER BY AD_AttachmentEntry_ID ASC NULLS LAST
        SQL params: [1254810]
        at org.adempiere.ad.dao.impl.TypedSqlQuery.list(TypedSqlQuery.java:323)
        at org.compiere.model.IQuery.stream(IQuery.java:507)
        at de.metas.attachments.impl.AttachmentDAO.retrieveAttachmentEntries(AttachmentDAO.java:78)
        at de.metas.attachments.impl.AttachmentBL.getEntries(AttachmentBL.java:308)
        at de.metas.ui.web.attachments.DocumentAttachments.toJson(DocumentAttachments.java:107)
        at de.metas.ui.web.attachments.DocumentAttachmentsRestController.getAttachments(DocumentAttachmentsRestController.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
                                                                                                                                              16152,2-9     89%
  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
a
```

**Comment by teosarca** [comment]
note to IT:
* regression on swing, webui and ZK: attach files, delete them etc
* test this task: pls make sure, for a given document, you have A LOT of HUGE attachments.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. attach a high number of big files to a doc, check the attached files in the doc in WebUI:
* Loading indicator: appeared for about 3 seconds only the first time, after that the files were displayed directly: OK
* no error is thrown: OK
2. Attach / delete files, in WebUI & Swing, check:
* attaching & deleting works fine, OK
* files are displayed properly when opened: OK
* preview in Swing works fine: OK
3. ZK: will be tested in https://github.com/metasfresh/mo73/issues/332 by cris
