### ISSUE TITLE
error when you receive in production

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#600]
### Is this a bug or feature request?
bug
### What is the current behavior?
sometimes, you get an error when you receive in production
#### Which are the steps to reproduce?
1. create and complete a new pp order (for a salad)
window: https://w101.metasfresh.com:8443/window/53009?viewId=53009-03202af1f23443c28639197593979eb7&page=1
2. select the line and do issue-receipt
3. select the co-product and issue an LU
4. move directly on main product and receive hu
=> modal opens with packvorschrift produkt zuordnung being already blue and has an error
### What is the expected or desired behavior?
shall work like usually
see pics with normal case and error case
![normal receiving](https://user-images.githubusercontent.com/16001666/30591856-2ef3a9ce-9d4d-11e7-8dc8-238b7760882a.png)
vs
![unusual receiving](https://user-images.githubusercontent.com/16001666/30591858-31d965fc-9d4d-11e7-8fa5-cba4e44967e9.png)

**Comment by teosarca** [comment]
The error is
```
2017-09-22 13:41:49.845 ERROR 24976 [                ][          ] --- [http-nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.adempiere.exceptions.AdempiereException: Failed invoking public de.metas.ui.web.window.datatypes.LookupValuesList de.metas.ui.web.pporder.process.WEBUI_PP_Order_Receipt.getM_HU_PI_Item_Products() using [Ljava.lang.Object;@69ade3cd] with root cause

org.adempiere.exceptions.AdempiereException: Receiving is not allowed
        at de.metas.ui.web.pporder.process.WEBUI_PP_Order_Receipt.createDefaultLUTUConfigManager(WEBUI_PP_Order_Receipt.java:136)
        at de.metas.ui.web.pporder.process.WEBUI_PP_Order_Receipt.getPackingInfoParams(WEBUI_PP_Order_Receipt.java:92)
        at de.metas.ui.web.pporder.process.WEBUI_PP_Order_Receipt.getM_HU_PI_Item_Products(WEBUI_PP_Order_Receipt.java:216)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at de.metas.ui.web.process.adprocess.WebuiProcessClassInfo.retriveLookupValues(WebuiProcessClassInfo.java:261)
        at de.metas.ui.web.process.adprocess.WebuiProcessClassInfo.lambda$createParamLookupValuesProvider$3(WebuiProcessClassInfo.java:235)
        at de.metas.ui.web.window.descriptor.ListLookupDescriptor.retrieveEntities(ListLookupDescriptor.java:130)
        at de.metas.ui.web.window.model.lookup.LookupDataSourceAdapter.findEntities(LookupDataSourceAdapter.java:101)
        at de.metas.ui.web.window.model.lookup.LookupDataSourceAdapter.findEntities(LookupDataSourceAdapter.java:79)
        at de.metas.ui.web.window.model.lookup.LookupDataSource.findEntities(LookupDataSource.java:54)
        at de.metas.ui.web.window.model.DocumentField.getLookupValues(DocumentField.java:425)
        at de.metas.ui.web.window.model.Document.getFieldLookupValues(Document.java:1503)
        at de.metas.ui.web.process.adprocess.ADProcessInstanceController.getParameterLookupValues(ADProcessInstanceController.java:229)
        at de.metas.ui.web.process.ProcessRestController.lambda$getParameterDropdown$12(ProcessRestController.java:321)
        at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceReadonly(ADProcessInstancesRepository.java:353)
        at de.metas.ui.web.process.ProcessRestController.getParameterDropdown(ProcessRestController.java:321)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
```

**Comment by teosarca** [comment]
shall be fixed by https://github.com/metasfresh/metasfresh-webui-frontend/issues/1214

**Comment by metas-dh** [comment]
this has been working fine for a long time now, so i'm closing this task.
