### ISSUE TITLE
WebUI Scheduler Window Log Subtab: Invalid Client ID=0

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#625]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When Opening the Log Subtab in Scheduler Window in WebUI, sometimes an Error occurs: Invalid AD_Client_ID = 0
#### Which are the steps to reproduce?
Open https://w101.metasfresh.com:8443/window/305/1000007 Subtab Log/ Protokoll and see.
### What is the expected or desired behavior?
Avoid the Error.

![image](https://user-images.githubusercontent.com/13365687/31386952-f4cd05e2-adc8-11e7-8101-98d8a3733a92.png)

**Comment by teosarca** [comment]
Reason: there are some AD_ScheduleLog records where AD_Client_ID=0 and AD_Org_ID=1000000 which is not valid.

Query to identify:
```
select s.Name, p.Classname, l.* from AD_SchedulerLog l
inner join AD_Scheduler s on (s.AD_Scheduler_ID=l.AD_Scheduler_ID)
inner join AD_Process p on (p.AD_Process_ID=s.AD_Process_ID)
where true
and l.AD_Client_ID=0 and l.AD_Org_ID > 0
-- and s.AD_Scheduler_ID=1000007
order by l.AD_Scheduler_ID
```

Query to fix (i.e. set AD_Org_ID=0):
```
update AD_SchedulerLog set AD_Org_ID=0 where AD_Client_ID=0 and AD_Org_ID > 0;
```

NOTE: fix applied to w101 directly

**Comment by teosarca** [comment]
for reference, the stacktrace was:
```
java.lang.IllegalArgumentException: Invalid AD_Client_ID=0 / AD_Org_ID=1000000
        at org.adempiere.ad.security.TableAccessLevel.forClientOrg(TableAccessLevel.java:99)
        at org.adempiere.ad.security.impl.UserRolePermissions.checkCanAccessRecord(UserRolePermissions.java:1020)
        at org.adempiere.ad.security.impl.UserRolePermissions.checkCanUpdate(UserRolePermissions.java:981)
        at de.metas.ui.web.window.controller.DocumentPermissionsHelper.checkCanEdit(DocumentPermissionsHelper.java:203)
        at de.metas.ui.web.window.controller.DocumentPermissionsHelper.canEdit(DocumentPermissionsHelper.java:171)
        at de.metas.ui.web.window.datatypes.json.JSONDocumentPermissions.lambda$isReadonly$0(JSONDocumentPermissions.java:86)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
        at de.metas.ui.web.window.datatypes.json.JSONDocumentPermissions.isReadonly(JSONDocumentPermissions.java:86)
        at de.metas.ui.web.window.datatypes.json.JSONDocumentPermissions.apply(JSONDocumentPermissions.java:51)
        at de.metas.ui.web.window.datatypes.json.JSONDocument.lambda$ofDocument$1(JSONDocument.java:90)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
```

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 / w101

still happening:

![2017-10-25 17_03_42-metasfresh](https://user-images.githubusercontent.com/18696715/32006293-b8f38f5c-b9a6-11e7-8c6b-8370d218ea21.png)

![2017-10-25 17_05_00-metasfresh](https://user-images.githubusercontent.com/18696715/32006302-c09e935a-b9a6-11e7-8d53-d48cbb36de3c.png)

**Comment by teosarca** [comment]
update: still cannot reproduce. Checked 
https://w101.metasfresh.com:8443/window/305/1000007
https://mf15cloudit/window/305/1000007

and they look fine (no errors).

----
If the problem happens again, i think we can try fixing the root cause,
i.e.  why when org.compiere.server.Scheduler.saveLogs(int, String) creates the AD_SchedulerLog, it sets AD_Org_ID>0 but AD_Client_ID remains zero.

**Comment by metas-dh** [comment]
Results of IT2

checked again: looks fine for both 
https://w101.metasfresh.com:8443/window/305/1000007
https://mf15cloudit/window/305/1000007
