### ISSUE TITLE
Can't add logo for organization in webui

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh-webui-api#638]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Can;t add logo
#### Which are the steps to reproduce?
Try to add an image as logo in organization.
You get this:
```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.adempiere.exceptions.AdempiereException: Failed building where clause because there is no Key Column defined in SqlDocumentEntityDataBindingDescriptor{sqlTableName=AD_OrgInfo, sqlTableAlias=d1}] with root cause

org.adempiere.exceptions.AdempiereException: Failed building where clause because there is no Key Column defined in SqlDocumentEntityDataBindingDescriptor{sqlTableName=AD_OrgInfo, sqlTableAlias=d1}
	at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.buildSqlWhereClause(SqlDocumentQueryBuilder.java:396)
	at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.getSqlWhereAndParams(SqlDocumentQueryBuilder.java:362)
	at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.buildSql(SqlDocumentQueryBuilder.java:299)
	at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.getSqlAndParams(SqlDocumentQueryBuilder.java:279)
	at de.metas.ui.web.window.model.sql.SqlDocumentQueryBuilder.getSql(SqlDocumentQueryBuilder.java:266)
	at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.retriveDocuments(SqlDocumentsRepository.java:172)
	at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.retrieveDocument(SqlDocumentsRepository.java:257)
	at de.metas.ui.web.window.model.DocumentQuery$Builder.retriveDocumentOrNull(DocumentQuery.java:196)
	at de.metas.ui.web.window.model.HighVolumeReadWriteIncludedDocumentsCollection.getDocumentById(HighVolumeReadWriteIncludedDocumentsCollection.java:199)
	at de.metas.ui.web.window.model.Document.getIncludedDocument(Document.java:1514)
	at de.metas.ui.web.window.controller.WindowRestController.lambda$7(WindowRestController.java:244)
	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentReadonly(DocumentCollection.java:219)
	at de.metas.ui.web.window.controller.WindowRestController.getData(WindowRestController.java:232)
	at de.metas.ui.web.window.controller.WindowRestController.getData(WindowRestController.java:219)
```
### What is the expected or desired behavior?
To be able to add a logo

**Comment by teosarca** [comment]
note to dev: introduce AD_OrgInfo.AD_OrgInfo_ID.
As a quick workaround (not sure if it's working) u could convert the AD_Org_ID to PK.
