### ISSUE TITLE
Error in manufacturing /issueing: Assumption failure: qty not null

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#712]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When trying to issue a product in manufacturing, window/53009, you sometimes get this error:
>Server error
>Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
>Bitte leiten Sie diese Meldung an metas weiter: Assumption failure: qty not 

Afterwards, you can't issue anymore, and you can't use the PP_Order anymore (error pops up again when clicking Produzieren in Action button)
#### Which are the steps to reproduce?
That's how i could reproduce the error:
1. Create 2 PP_Orders, same product, same BOM etc.
2. Have products to issue:
* product with CUs on LU, no TU
* product with only CUs
* product with CUs on TU(s), on an LU
3. Try the 1st PP_Order:
4. In Manufacturing modal window, HU select window, select the product with CUs on LU, no TU:
=> Server error, you cannot issue anything / receive anything / open the PP_Order modal window again after closing, always Server error
5. Try the 2nd PP_Order
6.  In Manufacturing modal window, HU select window, select 
* product with only CUs
* product with CUs on TU(s), on an LU
=> both working fine, no error
### What is the expected or desired behavior?
No error when issueing.

**Comment by metas-ts** [comment]
Her is the stacktrace

```
Assumption failure: qty not null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.adempiere.util.Check.mkEx(Check.java:109)
        at org.adempiere.util.Check.throwOrLogEx(Check.java:120)
        at org.adempiere.util.Check.assume(Check.java:163)
        at org.adempiere.util.Check.assumeNotNull(Check.java:258)
        at org.adempiere.util.Check.assumeNotNull(Check.java:244)
        at de.metas.quantity.Quantity.<init>(Quantity.java:80)
        at de.metas.quantity.Quantity.<init>(Quantity.java:75)
        at de.metas.ui.web.pporder.PPOrderLinesLoader.computeQuantityForHuPPOrderLineRow(PPOrderLinesLoader.java:369)
        at de.metas.ui.web.pporder.PPOrderLinesLoader.createForHUViewRecordRecursively(PPOrderLinesLoader.java:320)
        at de.metas.ui.web.pporder.PPOrderLinesLoader.lambda$createForHUViewRecordRecursively$5(PPOrderLinesLoader.java:323)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at de.metas.ui.web.pporder.PPOrderLinesLoader.createForHUViewRecordRecursively(PPOrderLinesLoader.java:328)
        at de.metas.ui.web.pporder.PPOrderLinesLoader.createForPPOrderQty(PPOrderLinesLoader.java:311)
        at de.metas.ui.web.pporder.PPOrderLinesLoader.lambda$createIncludedRowsForPPOrderQtys$4(PPOrderLinesLoader.java:302)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Collections$2.tryAdvance(Collections.java:4717)
        at java.util.Collections$2.forEachRemaining(Collections.java:4725)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at de.metas.ui.web.pporder.PPOrderLinesLoader.createIncludedRowsForPPOrderQtys(PPOrderLinesLoader.java:303)
        at de.metas.ui.web.pporder.PPOrderLinesLoader.createRowForBOMLine(PPOrderLinesLoader.java:261)
        at de.metas.ui.web.pporder.PPOrderLinesLoader.lambda$createRowsForBomLines$3(PPOrderLinesLoader.java:152)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at de.metas.ui.web.pporder.PPOrderLinesLoader.createRowsForBomLines(PPOrderLinesLoader.java:161)
        at de.metas.ui.web.pporder.PPOrderLinesLoader.retrieveData(PPOrderLinesLoader.java:126)
        at de.metas.ui.web.pporder.PPOrderLinesViewDataSupplier.lambda$new$0(PPOrderLinesViewDataSupplier.java:52)
        at org.adempiere.util.lang.ExtendedMemorizingSupplier.get(ExtendedMemorizingSupplier.java:66)
        at de.metas.ui.web.pporder.PPOrderLinesViewDataSupplier.getData(PPOrderLinesViewDataSupplier.java:57)
        at de.metas.ui.web.pporder.PPOrderLinesView.getData(PPOrderLinesView.java:362)
        at de.metas.ui.web.pporder.PPOrderLinesView.getPage(PPOrderLinesView.java:221)
        at de.metas.ui.web.view.ViewRestController.getViewData(ViewRestController.java:232)
        at sun.reflect.GeneratedMethodAccessor254.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
```
