### ISSUE TITLE
Error in Picking Tray Clearing when adding to existing HU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#804]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When clearing Picking Tray and adding to existing HU, an Assumption error appears.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
See the Stack Trace:
```
org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Assumption failure: qty >= 0 ({})
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.adempiere.util.Check.mkEx(Check.java:108)
        at org.adempiere.util.Check.throwOrLogEx(Check.java:119)
        at org.adempiere.util.Check.assume(Check.java:162)
        at org.adempiere.util.Check.assume(Check.java:146)
        at de.metas.handlingunits.allocation.impl.MutableAllocationResult.<init>(MutableAllocationResult.java:62)
        at de.metas.handlingunits.allocation.impl.AllocationUtils.createMutableAllocationResult(AllocationUtils.java:66)
        at de.metas.handlingunits.allocation.impl.AllocationUtils.createMutableAllocationResult(AllocationUtils.java:78)
        at de.metas.handlingunits.allocation.impl.AbstractFIFOStrategy.execute(AbstractFIFOStrategy.java:64)
        at de.metas.handlingunits.allocation.impl.AbstractFIFOStrategy.allocateOnIncludedHU(AbstractFIFOStrategy.java:232)
        at de.metas.handlingunits.allocation.impl.AbstractFIFOStrategy.allocateOnNewVHU(AbstractFIFOStrategy.java:217)
        at de.metas.handlingunits.allocation.impl.AbstractFIFOStrategy.allocateOnMaterialItem(AbstractFIFOStrategy.java:196)
        at de.metas.handlingunits.allocation.impl.AbstractFIFOStrategy.execute(AbstractFIFOStrategy.java:92)
        at de.metas.handlingunits.allocation.impl.AbstractFIFOStrategy.allocateOnIncludedHU(AbstractFIFOStrategy.java:232)
        at de.metas.handlingunits.allocation.impl.AbstractFIFOStrategy.allocateOnIncludedHUItem(AbstractFIFOStrategy.java:146)
        at de.metas.handlingunits.allocation.impl.AbstractFIFOStrategy.execute(AbstractFIFOStrategy.java:103)
        at de.metas.handlingunits.allocation.impl.HUListAllocationSourceDestination.processRequest(HUListAllocationSourceDestination.java:213)
        at de.metas.handlingunits.allocation.impl.HUListAllocationSourceDestination.load(HUListAllocationSourceDestination.java:175)
        at de.metas.handlingunits.allocation.impl.HULoader.loadToDestination(HULoader.java:356)
        at de.metas.handlingunits.allocation.impl.HULoader.unloadSourceThenLoadDestination(HULoader.java:305)
        at de.metas.handlingunits.allocation.impl.HULoader.access$000(HULoader.java:65)
        at de.metas.handlingunits.allocation.impl.HULoader$1.process(HULoader.java:199)
        at de.metas.handlingunits.allocation.impl.HUContextProcessorExecutor$1.run(HUContextProcessorExecutor.java:104)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:500)
        at de.metas.handlingunits.allocation.impl.HUContextProcessorExecutor.run(HUContextProcessorExecutor.java:81)
        at de.metas.handlingunits.allocation.impl.HULoader.processInHUContext(HULoader.java:224)
        at de.metas.handlingunits.allocation.impl.HULoader.load(HULoader.java:188)
         at de.metas.ui.web.pickingslotsClearing.process.WEBUI_PickingSlotsClearingView_TakeOutHUAndAddToHU.doIt(WEBUI_PickingSlotsClearingView_TakeOutHUAndAddToHU.java:127)
        at de.metas.process.JavaProcess.startProcess(JavaProcess.java:293)
        at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:563)
        at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:459)
        at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:49)
        at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:223)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
```

**Comment by metas-ts** [comment]
Cherry-picked to `2018-06`

**Comment by teosarca** [comment]
@metas-ts i think this one shall be in Testing. Moving it.

**Comment by metas-lc** [comment]
IT
checked out all add to hu actions in Picking Tray Clearing => no errors OK
