### ISSUE TITLE
Business Partner Pharma Product Create New Issue

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#945]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, it's not possible to create a new Business Partner product record in Business partner Pharma window. Example: https://w101.metasfresh.com:8443/window/540409/2156438
Same Subtab + Data can be created in Business partner Window without issues:
```

"java.lang.IllegalArgumentException: Invalid AD_Client_ID=1000000 / AD_Org_ID=-1"
1
:
"	at org.adempiere.ad.security.TableAccessLevel.forClientOrg(TableAccessLevel.java:99)"
2
:
"	at org.adempiere.ad.security.impl.UserRolePermissions.checkCanAccessRecord(UserRolePermissions.java:1020)"
3
:
"	at org.adempiere.ad.security.impl.UserRolePermissions.checkCanUpdate(UserRolePermissions.java:981)"
4
:
"	at de.metas.ui.web.window.controller.DocumentPermissionsHelper.checkCanEdit(DocumentPermissionsHelper.java:209)"
5
:
"	at de.metas.ui.web.window.controller.DocumentPermissionsHelper.canEdit(DocumentPermissionsHelper.java:177)"
6
:
"	at de.metas.ui.web.window.datatypes.json.JSONDocumentPermissions.lambda$isReadonly$0(JSONDocumentPermissions.java:85)"
7
:
"	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)"
8
:
"	at de.metas.ui.web.window.datatypes.json.JSONDocumentPermissions.isReadonly(JSONDocumentPermissions.java:85)"
9
:
"	at de.metas.ui.web.window.datatypes.json.JSONDocumentPermissions.apply(JSONDocumentPermissions.java:50)"
10
:
"	at de.metas.ui.web.window.datatypes.json.JSONDocument.lambda$ofDocument$1(JSONDocument.java:86)"
11
:
"	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)"
12
:
"	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)"
13
:
"	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)"
14
:
"	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)"
15
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
16
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
17
:
"	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)"
18
:
"	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)"
19
:
"	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
20
:
"	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)"
21
:
"	at de.metas.ui.web.window.datatypes.json.JSONDocument.ofDocument(JSONDocument.java:87)"
22
:
"	at de.metas.ui.web.window.datatypes.json.JSONDocument.lambda$ofDocumentsList$3(JSONDocument.java:164)"
23
:
"	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)"
24
:
"	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)"
25
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
26
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
27
:
"	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)"
28
:
"	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
29
:
"	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)"
30
:
"	at de.metas.ui.web.window.datatypes.json.JSONDocument.ofDocumentsList(JSONDocument.java:165)"
31
:
"	at de.metas.ui.web.window.controller.WindowRestController.lambda$getData$4(WindowRestController.java:256)"
32
:
"	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentReadonly(DocumentCollection.java:218)"
33
:
"	at de.metas.ui.web.window.controller.WindowRestController.getData(WindowRestController.java:237)"
34
:
"	at de.metas.ui.web.window.controller.WindowRestController.getData(WindowRestController.java:209)"
35
:
"	at sun.reflect.GeneratedMethodAccessor234.invoke(Unknown Source)"
36
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
37
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
38
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
39
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
40
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
41
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
42
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
43
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
44
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
45
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
46
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
47
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
48
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
49
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
50
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
51
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
52
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
53
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
54
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
55
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
56
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
57
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
58
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
60
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
61
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
62
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
63
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
65
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
66
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
67
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
69
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
70
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
71
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
73
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
74
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
75
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
76
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
77
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
78
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
79
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
81
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
82
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
83
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
85
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
86
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
87
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
89
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
90
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
91
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
92
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
93
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
94
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
95
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
96
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
97
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
98
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
99
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
[100 … 113]
100
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
101
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
102
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
103
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
104
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
105
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
106
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
107
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
108
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
109
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
110
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
111
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
112
:
"	at java.lang.Thread.run(Thread.java:748)"
```
 
#### Which are the steps to reproduce?
Open, try and see.

### What is the expected or desired behavior?
Shall work.

**Comment by teosarca** [comment]
the actual error is
```
org.adempiere.ad.expression.exceptions.ExpressionEvaluationException: Got no result for select ad_org_id from M_Product where M_Product_ID = @M_Product_ID/-1@ (SQL: select ad_org_id from M_Product where M_Product_ID = 0)
	at sun.reflect.GeneratedConstructorAccessor2637.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java)
	at com.zeroturnaround.jrebelbase.facade.p.invokeNewConstructor(SourceFile:156)
	at org.adempiere.ad.expression.exceptions.ExpressionEvaluationException.<init>(ExpressionEvaluationException.java:65534)
	at de.metas.ui.web.window.descriptor.sql.SqlDefaultValueExpression.evaluate(SqlDefaultValueExpression.java:191)
	at de.metas.ui.web.window.model.Document$InitialFieldValueSupplier.getValue(Document.java:679)
	at de.metas.ui.web.window.model.Document.initializeField(Document.java:490)
	at de.metas.ui.web.window.model.Document.initializeFields(Document.java:408)
	at de.metas.ui.web.window.model.Document.access$5(Document.java:393)
	at de.metas.ui.web.window.model.Document$Builder.build(Document.java:2088)
	at de.metas.ui.web.window.model.Document$Builder.initializeAsNewDocument(Document.java:2148)
	at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.createNewDocument(SqlDocumentsRepository.java:313)
	at de.metas.ui.web.window.model.HighVolumeReadWriteIncludedDocumentsCollection.createNewDocument(HighVolumeReadWriteIncludedDocumentsCollection.java:264)
```

**Comment by metas-lc** [comment]
IT
works now, but it makes the entry on org 0. Is that OK?
if i add a new one from bpartner window, it's made with 1000000

**Comment by teosarca** [comment]
TODO: have a callout which is triggered when the product it's set and it is setting AD_Org_ID from that product.

**Comment by metas-lc** [comment]
created followup: https://github.com/metasfresh/metasfresh-webui-api/issues/949
closing this one because there are no errors anymore OK
